package com.muqui.corona.model;
// Generated 28/11/2016 05:08:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EstadisticaEquipo generated by hbm2java
 */
@Entity
@Table(name="estadistica_equipo", uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class EstadisticaEquipo  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public EstadisticaEquipo() {
    }

    public EstadisticaEquipo(String nombre) {
       this.nombre = nombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


