package com.muqui.corona.model;
// Generated 28/11/2016 05:08:27 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.annotations.Proxy;

/**
 * EstadisticaPartido generated by hbm2java
 */
@Entity
@Table(name = "estadistica_partido")

public class EstadisticaPartido implements Serializable {

    private Integer id;
    private EstadisticaTorneo estadisticaTorneo;
    private String local;
    private int goleslocal;
    private String visita;
    private int golesvisita;
    private Date fecha;
    private String jornada;
    private String estadio;

    private String fechaCadena;
    private String torneo;

    public EstadisticaPartido() {
    }

    public EstadisticaPartido(EstadisticaTorneo estadisticaTorneo, String local, int goleslocal, String visita, int golesvisita, Date fecha, String jornada, String estadio) {
        this.estadisticaTorneo = estadisticaTorneo;
        this.local = local;
        this.goleslocal = goleslocal;
        this.visita = visita;
        this.golesvisita = golesvisita;
        this.fecha = fecha;
        this.jornada = jornada;
        this.estadio = estadio;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)  //aqui cambie
    @JsonIgnore
    @JoinColumn(name = "estadistica_torneo_id", nullable = false)
    public EstadisticaTorneo getEstadisticaTorneo() {
        return this.estadisticaTorneo;
    }

    public void setEstadisticaTorneo(EstadisticaTorneo estadisticaTorneo) {
        this.estadisticaTorneo = estadisticaTorneo;
    }

    @Column(name = "local", nullable = false, length = 45)
    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    @Column(name = "goleslocal", nullable = false)
    public int getGoleslocal() {
        return this.goleslocal;
    }

    public void setGoleslocal(int goleslocal) {
        this.goleslocal = goleslocal;
    }

    @Column(name = "visita", nullable = false, length = 45)
    public String getVisita() {
        return this.visita;
    }

    public void setVisita(String visita) {
        this.visita = visita;
    }

    @Column(name = "golesvisita", nullable = false)
    public int getGolesvisita() {
        return this.golesvisita;
    }

    public void setGolesvisita(int golesvisita) {
        this.golesvisita = golesvisita;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * @return the jornada
     */
    @Column(name = "jornada", nullable = false, length = 10)
    public String getJornada() {
        return jornada;
    }

    /**
     * @param jornada the jornada to set
     */
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }

    /**
     * @return the estadio
     */
    @Column(name = "estadio", nullable = false, length = 45)
    public String getEstadio() {
        return estadio;
    }

    /**
     * @param estadio the estadio to set
     */
    public void setEstadio(String estadio) {
        this.estadio = estadio;
    }

    /**
     * @return the torneo
     */
    @Transient
    public String getTorneo() {
        return torneo;
    }

    /**
     * @param torneo the torneo to set
     */
    public void setTorneo(String torneo) {
        this.torneo = torneo;
    }

    /**
     * @return the fechaCadena
     */
    @Transient
    public String getFechaCadena() {
        return fechaCadena;
    }

    /**
     * @param fechaCadena the fechaCadena to set
     */
    public void setFechaCadena(String fechaCadena) {
        this.fechaCadena = fechaCadena;
    }

}
