package com.muqui.corona.model;
// Generated 28/11/2016 05:08:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.annotations.Proxy;

/**
 * EstadisticaTorneo generated by hbm2java
 */
@Entity
@Table(name="estadistica_torneo" , uniqueConstraints = @UniqueConstraint(columnNames="nombre") )

public class EstadisticaTorneo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String pais;
     private Set<EstadisticaPartido> estadisticaPartidos = new HashSet<EstadisticaPartido>(0);

    public EstadisticaTorneo() {
    }

	
    public EstadisticaTorneo(String nombre, String pais) {
        this.nombre = nombre;
        this.pais = pais;
    }
    public EstadisticaTorneo(String nombre, String pais, Set<EstadisticaPartido> estadisticaPartidos) {
       this.nombre = nombre;
       this.pais = pais;
       this.estadisticaPartidos = estadisticaPartidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="pais", nullable=false, length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="estadisticaTorneo" , cascade = CascadeType.ALL)
@JsonIgnore
    public Set<EstadisticaPartido> getEstadisticaPartidos() {
        return this.estadisticaPartidos;
    }
    
    public void setEstadisticaPartidos(Set<EstadisticaPartido> estadisticaPartidos) {
        this.estadisticaPartidos = estadisticaPartidos;
    }




}


