package com.muqui.corona.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jugadorresultados generated by hbm2java
 */
@Entity
@Table(name="jugadorresultados")
public class Jugadorresultados  implements java.io.Serializable {


     private Integer idjugadorResultados;
     private Jugador jugador;
     private Partidos partidos;
     private Quiniela quiniela;
     private String  resultado;
    

    public Jugadorresultados() {
    }

    public Jugadorresultados(Jugador jugador, Partidos partidos, Quiniela quiniela, String resultado) {
       this.jugador = jugador;
       this.partidos = partidos;
       this.quiniela = quiniela;
       this.resultado = resultado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idjugadorResultados", unique=true, nullable=false)
    public Integer getIdjugadorResultados() {
        return this.idjugadorResultados;
    }
    
    public void setIdjugadorResultados(Integer idjugadorResultados) {
        this.idjugadorResultados = idjugadorResultados;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jugar_idjugar", nullable=false)
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="partidos_idpartidos", nullable=false)
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="quiniela_idquiniela", nullable=false)
    public Quiniela getQuiniela() {
        return this.quiniela;
    }
    
    public void setQuiniela(Quiniela quiniela) {
        this.quiniela = quiniela;
    }

    
    @Column(name="resultado", nullable=false, length=1)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


