package com.muqui.corona.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.validator.constraints.NotEmpty;


/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name="jugador")
public class Jugador  implements java.io.Serializable {


     private Integer idjugar;
     private Quiniela quiniela;
     private Users users;
     private String jugador;
     private String codigo;
     private int aciertos;
     private Set<Jugadorresultados> jugadorresultadoses = new HashSet<Jugadorresultados>(0);

    public Jugador() {
    }

	
    public Jugador(Quiniela quiniela, Users users, String jugador, String codigo, int aciertos) {
        this.quiniela = quiniela;
        this.users = users;
        this.jugador = jugador;
        this.codigo = codigo;
        this.aciertos = aciertos;
    }
    public Jugador(Quiniela quiniela, Users users, String jugador, String codigo, int aciertos, Set<Jugadorresultados> jugadorresultadoses) {
       this.quiniela = quiniela;
       this.users = users;
       this.jugador = jugador;
       this.codigo = codigo;
       this.aciertos = aciertos;
       this.jugadorresultadoses = jugadorresultadoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idjugar", unique=true, nullable=false)
    public Integer getIdjugar() {
        return this.idjugar;
    }
    
    public void setIdjugar(Integer idjugar) {
        this.idjugar = idjugar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="quiniela_idquiniela", nullable=false)
    public Quiniela getQuiniela() {
        return this.quiniela;
    }
    
    public void setQuiniela(Quiniela quiniela) {
        this.quiniela = quiniela;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_username", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @NotEmpty
    @Column(name="jugador", nullable=false, length=45)
    public String getJugador() {
        return this.jugador;
    }
    
    public void setJugador(String jugador) {
        this.jugador = jugador;
    }

    
    @Column(name="codigo", nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="aciertos", nullable=false)
    public int getAciertos() {
        return this.aciertos;
    }
    
    public void setAciertos(int aciertos) {
        this.aciertos = aciertos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jugador", cascade=CascadeType.ALL)

    public Set<Jugadorresultados> getJugadorresultadoses() {
        return this.jugadorresultadoses;
    }
    
    public void setJugadorresultadoses(Set<Jugadorresultados> jugadorresultadoses) {
        this.jugadorresultadoses = jugadorresultadoses;
    }




}


