package com.muqui.corona.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Quiniela generated by hbm2java
 */
@Entity
@Table(name = "quiniela")
public class Quiniela implements java.io.Serializable {

    private Integer idquiniela;
    private String paginaTipo;
    private String nombre;
    private Timestamp fechaLimite;
    private List<Partidos> partidoses = new LinkedList<Partidos>();
    private List<Jugador> jugadors = new LinkedList<Jugador>();
    private List<Jugadorresultados> jugadorresultadoses = new LinkedList<Jugadorresultados>();

    private String fechaTemporal;

    public Quiniela() {
    }

    public Quiniela(List<Partidos> partidos) {
        this.partidoses = partidos;

    }

    public Quiniela( String nombre) {
        
        this.nombre = nombre;
    }

    public Quiniela( String nombre, Timestamp fechaLimite, List<Partidos> partidoses, List<Jugador> jugadors, List<Jugadorresultados> jugadorresultadoses, String paginaTipo) {
        this.paginaTipo = paginaTipo;
        this.nombre = nombre;
        this.fechaLimite = fechaLimite;
        this.partidoses = partidoses;
        this.jugadors = jugadors;
        this.jugadorresultadoses = jugadorresultadoses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idquiniela", unique = true, nullable = false)
    public Integer getIdquiniela() {
        return this.idquiniela;
    }

    public void setIdquiniela(Integer idquiniela) {
        this.idquiniela = idquiniela;
    }

   

 

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

//    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_limite", length = 19)
    public Timestamp getFechaLimite() {
        return this.fechaLimite;
    }

    public void setFechaLimite(Timestamp fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "quiniela")
    public List<Partidos> getPartidoses() {
        return this.partidoses;
    }

    public void setPartidoses(List<Partidos> partidoses) {
        this.partidoses = partidoses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "quiniela")
    public List<Jugador> getJugadors() {
        return this.jugadors;
    }

    public void setJugadors(List<Jugador> jugadors) {
        this.jugadors = jugadors;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "quiniela")
    public List<Jugadorresultados> getJugadorresultadoses() {
        return this.jugadorresultadoses;
    }

    public void setJugadorresultadoses(List<Jugadorresultados> jugadorresultadoses) {
        this.jugadorresultadoses = jugadorresultadoses;
    }

    /**
     * @return the fechaTemporal
     */
    @Transient
    public String getFechaTemporal() {
        return fechaTemporal;
    }

    /**
     * @param fechaTemporal the fechaTemporal to set
     */
    public void setFechaTemporal(String fechaTemporal) {
        this.fechaTemporal = fechaTemporal;
    }

    /**
     * @return the paginaTipo
     */
    @Column(name = "pagina_tipo", nullable = false, length = 20)
    public String getPaginaTipo() {
        return paginaTipo;
    }

    /**
     * @param paginaTipo the paginaTipo to set
     */
    public void setPaginaTipo(String paginaTipo) {
        this.paginaTipo = paginaTipo;
    }

}
