package com.muqui.corona.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

    private String username;

    private String password;

    private String email;

    private boolean enabled;
    private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
    private Set<Pagina> paginas = new HashSet<Pagina>(0);
    private Set<Jugador> jugadors = new HashSet<Jugador>(0);

    private String passwordConfirm;
    private String pagina;

    public Users() {
    }

    public Users(String username, boolean enabled) {
        this.username = username;
        this.enabled = enabled;
    }

    public Users(String username, String password, boolean enabled, Set<UserRoles> userRoleses, Set<Pagina> paginas, Set<Jugador> jugadors) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
        this.userRoleses = userRoleses;
        this.paginas = paginas;
        this.jugadors = jugadors;
    }

    @Id
    @NotNull
    @Column(name = "username", unique = true, nullable = false, length = 45)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", length = 60)
    @NotNull
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "email", length = 60)
    @NotNull
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @NotNull
    @Column(name = "enabled", nullable = false)
    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users", cascade = CascadeType.REMOVE)
    
    @JsonIgnore
    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }

    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users", cascade = CascadeType.REMOVE)
    @JsonIgnore
    public Set<Pagina> getPaginas() {
        return this.paginas;
    }

    public void setPaginas(Set<Pagina> paginas) {
        this.paginas = paginas;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users", cascade = CascadeType.REMOVE)
    @JsonIgnore
    public Set<Jugador> getJugadors() {
        return this.jugadors;
    }

    public void setJugadors(Set<Jugador> jugadors) {
        this.jugadors = jugadors;
    }

    /**
     * @return the passwordConfirm
     */
    @Transient
    public String getPasswordConfirm() {
        return passwordConfirm;
    }

    /**
     * @param passwordConfirm the passwordConfirm to set
     */
    public void setPasswordConfirm(String passwordConfirm) {
        this.passwordConfirm = passwordConfirm;
    }

    /**
     * @return the pagina
     */
    @Transient
    public String getPagina() {
        return pagina;
    }

    /**
     * @param pagina the pagina to set
     */
    public void setPagina(String pagina) {
        this.pagina = pagina;
    }
}
